# Generated by Django 2.2.1 on 2019-05-29 08:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour', models.CharField(max_length=50, verbose_name='Flavour')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavors', related_query_name='flavors', to='outlets.Category')),
            ],
            options={
                'verbose_name_plural': 'Flavour',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Item')),
                ('uom', models.CharField(max_length=50, verbose_name='UOM')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('created_date', models.DateTimeField(verbose_name='Created Date')),
            ],
            options={
                'verbose_name_plural': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Outlet Name')),
                ('tax_type', models.CharField(choices=[('GST', 'GST'), ('TRN', 'TRN')], max_length=3)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=3)),
                ('country', models.CharField(choices=[('United Arab Emirates', 'United Arab Emirates'), ('India', 'India')], default='UAE', max_length=100, verbose_name='Country')),
                ('contact', models.CharField(help_text='Outlet Contact Number', max_length=50, verbose_name='Contact')),
                ('city', models.CharField(help_text='Province/State/Region', max_length=100, verbose_name='City')),
                ('street', models.CharField(max_length=100, verbose_name='Street Name')),
                ('longitude', models.FloatField(default=0.0, help_text='Longitude', verbose_name='Outlet Longitude')),
                ('latitude', models.FloatField(default=0.0, help_text='Latitude', verbose_name='Outlet Latitude')),
                ('thumbnail', models.ImageField(blank=True, default='', max_length=500, upload_to='', verbose_name='Thumbnail')),
                ('time_zone', models.CharField(max_length=100, verbose_name='Outlet Timezone')),
                ('currency', models.FloatField(choices=[(0.0, 'NRS'), (1.0, 'AED'), (2.0, 'USD'), (3.0, 'EUR'), (4.0, 'SAR'), (5.0, 'KWD'), (6.0, 'OMR'), (7.0, 'BHD')], default=1, help_text='Choose Currency', verbose_name='Currency')),
                ('delivery_area', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('okmandu1__Kathmandu', 'okmandu1'), ('youmandu2__Kathmandu', 'youmandu2'), ('gomandu3__Kathmandu', 'gomandu3'), ('Lupur1__Lalitpur', 'Lupur1'), ('kitpur2__Lalitpur', 'kitpur2'), ('palpur3__Lalitpur', 'palpur3'), ('Baktapur1__Bhaktapur', 'Baktapur1'), ('Bhakur2__Bhaktapur', 'Bhakur2'), ('Bhakr3__Bhaktapur', 'Bhakr3')], help_text='Approximately choose various delivery areas', max_length=171, null=True, verbose_name='Delivery Areas')),
                ('slug', models.SlugField(blank=True, help_text='Used to share your store among Customers', max_length=25, null=True, verbose_name='Short Display Name')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator('Enter a valid email. This value may contain only letters, numbers,and @/./+/-/_ characters.')], verbose_name='Outlet Contact E-mail')),
                ('connected_email', models.EmailField(blank=True, error_messages={'unique': 'Email address already exists'}, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator('Enter a valid email. This value may contain only letters, numbers,and @/./+/-/_ characters.')], verbose_name='Outlet Admin Contact E-mail')),
                ('registration', models.CharField(max_length=50, verbose_name='Outlet Registration ')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=100, verbose_name='Sub Category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.Category')),
            ],
            options={
                'verbose_name_plural': 'Sub-Category',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(max_length=25, verbose_name='Quantity')),
                ('sku', models.CharField(max_length=40, verbose_name='S.K.U stock code')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.Item')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.Outlet')),
            ],
            options={
                'verbose_name_plural': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='Size')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.Category')),
            ],
            options={
                'verbose_name_plural': 'Size',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('invite_reason', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.Group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.Person')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='associated_outlet',
            field=models.ManyToManyField(to='outlets.Outlet'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.Category'),
        ),
        migrations.AddField(
            model_name='item',
            name='flavour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.Flavour'),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.Size'),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.SubCategory'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='outlets.Membership', to='outlets.Person'),
        ),
    ]
